const BASEURL="http://localhost:8000/"
export const LOGIN_VERIFY_USER = BASEURL+"api/v1/user/"
export const GET_NEXT_QUESTION = BASEURL+"api/v1/user/getNextQuestion"
export const VERIFY_ANSWER=BASEURL+"api/v1/user/verifyAnswer"
export const END_TEST=BASEURL+"api/v1/user/endTest"
export const GET_ALL_QUESTION=BASEURL+"api/v1/user/getTotalQuestionCount"
export const ADMIN_LOGIN=BASEURL+"api/v1/admin"
export const GET_ALL_USERS=BASEURL+"api/v1/admin/getAllUsers"
export const GET_RESULT=BASEURL+"api/v1/admin/getResults"
export const RESET_USER=BASEURL+"api/v1/admin/resetData"

